// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_ger_wermachtwet_helm1"; // Dark special logos, rarest
	a[1] = "char_ger_wermachtwet_helm_cloth1"; // Dark camo
	a[2] = "char_ger_wermachtwet_helm_cloth1"; // Dark camo
	a[3] = "char_ger_wermachtwet_helm_cloth1"; // Dark camo

	return a;
}