// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0]  = "char_ger_wermachtwet_gear1";
	a[1]  = "char_ger_wermachtwet_gear2";
	a[2]  = "char_ger_wermachtwet_gear2";
	a[3]  = "char_ger_wermachtwet_gear2";
	a[4]  = "char_ger_wermachtwet_gear3";


	return a;
}