// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("char_jap_impinf_officer_body_zomb");
	self.headModel = "char_jap_impinf_officer_head";
	self attach(self.headModel, "", true);
	self.hatModel = "char_jap_impinf_officer_hat_zomb";
	self attach(self.hatModel);
	self.voice = "japanese";
}

precache()
{
	precacheModel("char_jap_impinf_officer_body_zomb");
	precacheModel("char_jap_impinf_officer_head");
	precacheModel("char_jap_impinf_officer_hat_zomb");
}
