// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0]  = "char_ger_wermachtwet_gear2"; // 30%
	a[1]  = "char_ger_wermachtwet_gear2";
	a[2]  = "char_ger_wermachtwet_gear2";
	a[3]  = "char_ger_wermachtwet_gear1"; // 20%
	a[4]  = "char_ger_wermachtwet_gear1"; 
	a[5]  = "char_ger_wermachtwet_gear3"; // 20%
	a[6]  = "char_ger_wermachtwet_gear3";
	a[7]  = "char_ger_honorgd_gear3"; // 30% wounded gear
	a[8]  = "char_ger_honorgd_gear3";
	a[9]  = "char_ger_honorgd_gear3";

	return a;
}
