// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_ger_wermachtwet_cap1"; // Dark cap, rarest
	a[1] = "char_ger_waffen_helm1_dark"; // Dark helm
	a[2] = "char_ger_waffen_helm1_dark"; // Dark helm
	a[3] = "char_ger_waffen_helm1_dark"; // Dark helm
	
	return a;
}