// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\char_jap_impinf_zombiebody5alias::main());
	self.headModel = codescripts\character::randomElement(xmodelalias\char_jap_impinf2_zombieheadalias::main());
	self attach(self.headModel, "", true);

	random = randomintrange(1,101);
	if( random <= 5) // 1,2,3,4,5 = 5% chance helmet
	{
		self.hatModel = "char_jap_impinf_body4_helm2";
		self attach(self.hatModel, "", true);
	}
	else if(random == 6) // 1% chance of special head band
	{
		self.hatModel = "char_jap_impinfwet_body4_hband";
		self attach(self.hatModel, "", true);	
	}

	self.voice = "japanese";
	self.torsoDmg1 = "char_jap_impinf_body5z_g_upclean";
	self.torsoDmg2 = codescripts\character::randomElement(xmodelalias\char_jap_impinf_mk_b5z_g_rarmoffalias::main());
	self.torsoDmg3 = codescripts\character::randomElement(xmodelalias\char_jap_impinf_mk_b5z_g_larmoffalias::main());
	self.torsoDmg4 = codescripts\character::randomElement(xmodelalias\char_jap_impinf_mk_b5z_g_torsoalias::main());
	self.torsoDmg5 = "char_jap_impinf_body5z_g_behead";
	self.legDmg1 = "char_jap_impinf_body5z_g_lowclean";
	self.legDmg2 = codescripts\character::randomElement(xmodelalias\char_jap_impinf_mk_b5z_g_rlegoffalias::main());
	self.legDmg3 = codescripts\character::randomElement(xmodelalias\char_jap_impinf_mk_b5z_g_llegoffalias::main());
	self.legDmg4 = codescripts\character::randomElement(xmodelalias\char_jap_impinf_mk_b5z_g_legsoffalias::main());
	self.gibSpawn1 = "char_jap_impinf_body5z_g_rarmspawn";
	self.gibSpawnTag1 = "J_Elbow_RI";
	self.gibSpawn2 = "char_jap_impinf_body5z_g_larmspawn";
	self.gibSpawnTag2 = "J_Elbow_LE";
	self.gibSpawn3 = "char_jap_impinf_body5z_g_rlegspawn";
	self.gibSpawnTag3 = "J_Knee_RI";
	self.gibSpawn4 = "char_jap_impinf_body5z_g_llegspawn";
	self.gibSpawnTag4 = "J_Knee_LE";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\char_jap_impinf_zombiebody5alias::main());
	codescripts\character::precacheModelArray(xmodelalias\char_jap_impinf2_zombieheadalias::main());
	precacheModel("char_jap_impinf_body4_helm2");
	precacheModel("char_jap_impinfwet_body4_hband");
	precacheModel("char_jap_impinf_body5z_g_upclean");
	codescripts\character::precacheModelArray(xmodelalias\char_jap_impinf_mk_b5z_g_rarmoffalias::main());
	codescripts\character::precacheModelArray(xmodelalias\char_jap_impinf_mk_b5z_g_larmoffalias::main());
	codescripts\character::precacheModelArray(xmodelalias\char_jap_impinf_mk_b5z_g_torsoalias::main());
	precacheModel("char_jap_impinf_body5z_g_behead");
	precacheModel("char_jap_impinf_body5z_g_lowclean");
	codescripts\character::precacheModelArray(xmodelalias\char_jap_impinf_mk_b5z_g_rlegoffalias::main());
	codescripts\character::precacheModelArray(xmodelalias\char_jap_impinf_mk_b5z_g_llegoffalias::main());
	codescripts\character::precacheModelArray(xmodelalias\char_jap_impinf_mk_b5z_g_legsoffalias::main());
	precacheModel("char_jap_impinf_body5z_g_rarmspawn");
	precacheModel("char_jap_impinf_body5z_g_larmspawn");
	precacheModel("char_jap_impinf_body5z_g_rlegspawn");
	precacheModel("char_jap_impinf_body5z_g_llegspawn");
	precacheModel("char_jap_impinf_body5z_g_upclean");
	codescripts\character::precacheModelArray(xmodelalias\char_jap_impinf_mk_b5z_g_rarmoffalias::main());
	codescripts\character::precacheModelArray(xmodelalias\char_jap_impinf_mk_b5z_g_larmoffalias::main());
	codescripts\character::precacheModelArray(xmodelalias\char_jap_impinf_mk_b5z_g_torsoalias::main());
	precacheModel("char_jap_impinf_body5z_g_behead");
	precacheModel("char_jap_impinf_body5z_g_lowclean");
	codescripts\character::precacheModelArray(xmodelalias\char_jap_impinf_mk_b5z_g_rlegoffalias::main());
	codescripts\character::precacheModelArray(xmodelalias\char_jap_impinf_mk_b5z_g_llegoffalias::main());
	codescripts\character::precacheModelArray(xmodelalias\char_jap_impinf_mk_b5z_g_legsoffalias::main());
	precacheModel("char_jap_impinf_body5z_g_rarmspawn");
	precacheModel("char_jap_impinf_body5z_g_larmspawn");
	precacheModel("char_jap_impinf_body5z_g_rlegspawn");
	precacheModel("char_jap_impinf_body5z_g_llegspawn");
}
